#微服务端口配置
server:
  port: 8120

#spring相关配置
spring:
  profiles:
    active: dev
  application:
    name: service-sms
  #解决swagger报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认为8
        max-wait: -1ms  #没有限制
        max-idle: 8  #最大空闲连接
        min-idle: 0  #最小空闲连接
  #springcloud配置
  cloud:
    #nacos服务地址
    nacos:
      discovery:
       server-addr: localhost:8848
  #rabbitmq消息队列
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /srbhost
    username: srbuser
    password: #TODO


#容联云短信服务
ronglianyun:
  sms:
    accountSId: #TODO
    accountToken: #TODO
    appId: #TODO
    templateId: 1
    subAppend: 1210
    reqId: #TODO

#openFeign配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置，默认1秒超时太短了，设置为10s
        readTimeout: 600000 #执行超时配置
  #开启Feign对Sentinel的支持
  sentinel:
    enabled: true

#开启日志
logging:
  level:
    com.dry.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口
