#微服务端口配置
server:
  port: 8110

#spring相关配置
spring:
  profiles:
    active: dev #开发环境
  application:
    name: service-core
  #解决swagger报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置mysql连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  #配置redis连接
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认为8
        max-wait: -1ms  #没有限制
        max-idle: 8  #最大空闲连接
        min-idle: 0  #最小空闲连接
  #springcloud配置
  cloud:
    #nacos服务地址
    nacos:
      discovery:
        server-addr: localhost:8848
  #rabbitmq消息队列
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /srbhost
    username: srbuser
    password: 123456

# mybatis plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #设置日志
  mapper-locations:
    classpath:com/dry/srb/core/mapper/xml/*.xml

